# Generated by Django 5.2.7 on 2026-01-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Credential',
                'verbose_name_plural': 'ML Credentials',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=50)),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True)),
                ('hash_code', models.TextField(blank=True, null=True)),
                ('security_digit', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_qr_data', models.TextField(help_text='JSON raw del QR escaneado')),
                ('api_response', models.JSONField(blank=True, help_text='Respuesta completa de la API', null=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitoso'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
