# Generated by Django 5.2.7 on 2026-01-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLCredentials',
        ),
    ]
