# Generated by Django 5.2.7 on 2026-01-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_delete_mlcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='scanner_user',
            field=models.CharField(blank=True, help_text='Nombre de quien escaneó (Jose, Fede, etc)', max_length=50, null=True),
        ),
    ]
