# Generated by Django 5.2.10 on 2026-01-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scan_is_cancelled_scan_scanner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='current_status',
            field=models.CharField(blank=True, help_text='Estado actual (ESTADO ACTUAL - actualizado diariamente)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='initial_status',
            field=models.CharField(blank=True, help_text='Estado al momento del escaneo (ESTADO DE RETIRO)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='last_status_check',
            field=models.DateTimeField(blank=True, help_text='Última vez que se verificó el estado', null=True),
        ),
    ]
