# Generated by Django 5.2.10 on 2026-01-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_scan_current_status_scan_initial_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='order_status',
            field=models.CharField(blank=True, help_text='Estado del pedido/orden', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='current_status',
            field=models.CharField(blank=True, help_text='Estado del pedido actual (ESTADO ACTUAL - actualizado diariamente)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='initial_status',
            field=models.CharField(blank=True, help_text='Estado del pedido al momento del escaneo (ESTADO DE RETIRO)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='shipment_status',
            field=models.CharField(blank=True, help_text='Estado del envío físico', max_length=50, null=True),
        ),
    ]
