# Generated by Django 5.2.10 on 2026-01-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_scan_order_status_alter_scan_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='is_logistics',
            field=models.BooleanField(default=False, help_text='Es de logística externa (no ML)'),
        ),
        migrations.AddField(
            model_name='scan',
            name='logistics_customer_name',
            field=models.CharField(blank=True, help_text='Nombre completo del cliente', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='logistics_data',
            field=models.JSONField(blank=True, help_text='Datos completos del QR de logística', null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='logistics_type',
            field=models.CharField(blank=True, help_text='Tipo: PARTICULAR o CAMBIO', max_length=20, null=True),
        ),
    ]
