# Generated by Django 5.2.10 on 2026-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_scan_is_logistics_scan_logistics_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='shipping_mode',
            field=models.CharField(blank=True, help_text='flex, me2, mensajeria', max_length=20, null=True),
        ),
    ]
