# Generated by Django 5.2.10 on 2026-01-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_scan_shipping_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_count',
            field=models.IntegerField(default=1, help_text='Número de veces que se escaneó este código (para detectar 3er escaneo)'),
        ),
    ]
