# Generated by Django 5.2.4 on 2026-02-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_scan_scan_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremierShipmentCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(db_index=True, help_text='DID del envío (extraído del link público)', max_length=50)),
                ('customer_name', models.CharField(blank=True, help_text='Nombre del cliente', max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, help_text='PARTICULAR o CAMBIO', max_length=20, null=True)),
                ('raw_row_data', models.JSONField(blank=True, help_text='Datos completos extraídos de la fila/modal', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='Fecha/hora del pre-fetch')),
                ('used', models.BooleanField(default=False, help_text='Si ya fue consultado en un escaneo')),
            ],
            options={
                'verbose_name': 'Premier Cache',
                'verbose_name_plural': 'Premier Cache',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
